### ISSUE TITLE
Github CI on Windows should use ridk

### ISSUE THREAD

**Issue by jwillemsen** [RemedyIT/r2corba#70]
With ruby 2.4 or newer there is a ridk available that has a complete msys/mingw installastion, this could be used at the moment the newer ruby versions compile (see #69). Below is the simplified github CI action. We should also update our install instructions to refer to the ridk on windows.

```
name: windows

on:
  push:
  pull_request:
  schedule:
    - cron: '0 7 * * SUN'

jobs:
  build:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.4', '2.5', '2.6', '2.7', '3.0' ]
    name: ${{ matrix.runs-os }} ${{ matrix.msystem }} ruby-${{ matrix.ruby }}
    env:
      DOC_ROOT: ${{ github.workspace }}/ACE
      MPC_ROOT: ${{ github.workspace }}/ACE/MPC
      RIDL_ROOT: ${{ github.workspace }}/ridl
    steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: checkout r2corba
      uses: actions/checkout@v2
    - name: checkout ACE_TAO
      uses: actions/checkout@v2
      with:
        repository: DOCGroup/ACE_TAO
        path: ${{ env.DOC_ROOT }}
    - name: checkout MPC
      uses: actions/checkout@v2
      with:
        repository: DOCGroup/MPC
        path: ${{ env.MPC_ROOT }}
    - name: checkout ridl
      uses: actions/checkout@v2
      with:
        repository: RemedyIT/ridl
        path: ${{ env.RIDL_ROOT }}
    - name: Run rake configure
      run: |
        ridk exec rake configure
    - name: Run rake build
      run: |
        rake build
      shell: cmd
    - name: Run rake test
      run: |
        rake test
```
